### ISSUE TITLE
Installing coq-of-ocaml

### ISSUE THREAD

**Issue by MMY269** [formal-land/coq-of-ocaml#211]
Hi,
I can't install coq-of-ocaml. I got the error : 

"<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[coq-of-ocaml.dev] no changes from git+https://github.com/clarus/coq-of-ocaml.git#master

Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting"

**Comment by clarus** [comment]
OK, this is an error related to opam dependencies. What does `opam list`, `opam switch`, `opam repo` and `opam pin list` say? Also, you can try to install `coq-of-ocaml` without the pin using the version from the standard OCaml repository (`opam install coq-of-ocaml`).

**Comment by MMY269** [comment]
Thank you.

Below are the responses to the commands:

**opam list** 
# Packages matching: installed
# Name              # Installed # Synopsis
base-bigarray       base
base-bytes          base        Bytes library distributed with the OCaml compiler
base-threads        base
base-unix           base
bigarray-compat     1.1.0       Compatibility library to use Stdlib.Bigarray when 
biniou              1.2.1       Binary data format designed for speed, safety, eas
camlp5              7.14        Preprocessor-pretty-printer of OCaml
camomile            1.0.2       A Unicode library
charInfo_width      1.1.0       Determine column width for a character
conf-findutils      1           Virtual package relying on findutils
conf-perl           2           Virtual package relying on perl
coq-of-ocaml        2.3.0       Compile a subset of OCaml to Coq
cppo                1.6.8       Code preprocessor like cpp for OCaml
csexp               1.5.1       Parsing and printing of S-expressions in Canonical
dune                2.7.1       Fast, portable, and opinionated build system
dune-configurator   2.7.1       Helper library for gathering system configuration
easy-format         1.3.2       High-level and functional interface to the Format 
lambda-term         3.2.0       Terminal manipulation library for OCaml
lwt                 5.5.0       Promises and event-driven I/O
lwt_log             1.1.1       Lwt logging library (deprecated)
lwt_react           1.1.5       Helpers for using React with Lwt
mew                 0.1.0       Modal editing witch
mew_vi              0.5.0       Modal editing witch, VI interpreter
mmap                1.2.0       File mapping functionality
num                 1.4         The legacy Num library for arbitrary-precision int
ocaml               4.09.0      The OCaml compiler (virtual package)
ocaml-base-compiler 4.09.0      Official release 4.09.0
ocaml-config        1           OCaml Switch Configuration
ocamlbuild          0.14.1      OCamlbuild is a build system with builtin rules to
ocamlfind           1.9.3       A library manager for OCaml
ocplib-endian       1.2         Optimised functions to read and write int16/32/64 
react               1.2.2       Declarative events and signals for OCaml
result              1.5         Compatibility Result module
seq                 base        Compatibility package for OCaml's standard iterato
smart-print         0.3.0       A pretty-printing library in OCaml
topkg               1.0.5       The transitory OCaml software packager
trie                1.0.0       Strict impure trie tree
utop                2.9.0       Universal toplevel for OCaml
yojson              1.7.0       Yojson is an optimized parsing and printing librar
zed                 3.1.0       Abstract engine for text edition in OCaml

**opam switch**
#  switch     compiler                    description
→  coq-8.9.1  ocaml-base-compiler.4.09.0  coq-8.9.1
   default    ocaml-system.4.08.1         default

**opam repo** 
[NOTE] These are the repositories in use by the current switch. Use '--all' to
       see all configured repositories.

<><> Repository configuration for switch coq-8.9.1 ><><><><><><><><><><><><><><>
 1 default https://opam.ocaml.org

**opam pin list**
coq.8.9.1  (uninstalled)  version  8.9.1

~$ install coq-of-ocaml
install: opérande de fichier cible manquant après 'coq-of-ocaml'
Saisissez « install --help » pour plus d'informations.

~$ opam install coq-of-ocaml
[NOTE] Package coq-of-ocaml is already installed (current version is 2.3.0).

$ coq-of-ocaml main.ml 
coq-of-ocaml : commande introuvable

**Comment by clarus** [comment]
OK, so it is surprising that `opam list` shows `coq-of-ocaml` as installed but the command `coq-of-ocaml main.ml` does not run. Also `coq-of-ocaml` requires a different version of OCaml. If you try with OCaml 4.12.1 you should be able to install the latest version of `coq-of-ocaml`. I think that was the issue and the error message `opam` did not show it clearly. You can change your OCaml version with `opam switch create 4.12.1`.

**Comment by MMY269** [comment]
Thanks, problem solved.

**Comment by clarus** [comment]
Top
