### ISSUE TITLE
Error: Unbound type constructor 

### ISSUE THREAD

**Issue by MMY269** [formal-land/coq-of-ocaml#213]
Hi, 
I'm trying to transfer the OCaml code below (under a .mli file) to Coq and I got the error "Error: Unbound type constructor k" :

type 'a cont
val callcc: ('a cont -> 'a) -> 'a
val throw: 'a cont -> 'a -> 'b

let now () =
 let s = ref None in
 callcc (fun k -> s := Some k);
 s

 let past_travel_to date =
 match !date with
 | None -> assert false
 | Some date -> throw date ()

 let cake = ref `Cake
 let eat () =
 assert (!cake = `Cake);
 Printf.printf "I am eating the cake! Miamee!\n"
 cake := `NoMoreCake

 let _ =
 let t = now () in
 Printf.printf "I am in front of the cake\n.";
 eat ();
 past_travel_to t

Thanks for your help.

**Comment by clarus** [comment]
Hi, what is the full error message from the terminal?

**Comment by clarus** [comment]
It may be that your project is not compiled.

**Comment by MMY269** [comment]
Thank you for your reply.
The error message is: Error: Unbound type constructor k
The program I want to transfer is:
type 'a cont
val callcc: ('a cont -> 'a) -> 'a
val throw: 'a cont -> 'a -> 'b

let now () =
 let s = ref None in
 callcc (fun k -> s := Some k);
 s

 let past_travel_to date =
 match !date with
 | None -> assert false
 | Some date -> throw date ()

 let cake = ref `Cake
 let eat () =
 assert (!cake = `Cake);
 Printf.printf "I am eating the cake! Miamee!\n"
 cake := `NoMoreCake

 let _ =
 let t = now () in
 Printf.printf "I am in front of the cake\n.";
 eat ();
 past_travel_to t

**Comment by clarus** [comment]
Usually the error message is more complete with something like:
```
--- contract_manager_storage.ml:77:38 ------------------------------------------- merlin (20/27) ---

  75 |           Some (public_key, expected_hash, provided_hash)
  76 |       | _ -> None)
> 77 |     (fun (public_key, expected_hash, provided_hash) ->
  78 |       Inconsistent_hash {public_key; expected_hash; provided_hash}) ;
  79 |   register_error_kind
  80 |     `Branch


Error: Error (warning 27): unused variable provided_hash.
```

So I was asking for the complete version like this one. You may have an error related to the Merlin parser.

**Comment by MMY269** [comment]
When I tried to update I got:

$ opam upgrade --verbose
Everything as up-to-date as possible (run with --verbose to show unavailable
upgrades).

The following packages are not being upgraded because the new versions conflict
with other installed packages:
  - coq-of-ocaml.2.5.2+4.13
  - merlin.4.4.1~5.0preview
However, you may "opam upgrade" these packages explicitly, which will ask
permission to downgrade or uninstall the conflicting packages.
Nothing to do.
 
Which versions are compatible?

**Comment by MMY269** [comment]
I changed the version of merlin, I uninstalled it...
Always the same problem.
Is there a solution?

**Comment by MMY269** [comment]
Thank you for your help.
I don't know OCaml but I managed to compile the project. I just uploaded it to the link:
https://github.com/MMY269/TestCallCC_Coq

**Comment by MMY269** [comment]
Is there a manipulation to do to resolve the errors?

**Comment by MMY269** [comment]
I don't know how to compile you with Dune since just now I only have errors. :(

**Comment by clarus** [comment]
You can follow the instructions to setup a project here: https://dune.readthedocs.io/en/latest/quick-start.html

**Comment by MMY269** [comment]
I don't understand the part where there is a .ml library and we need to add modules_without_implementation .

**Comment by clarus** [comment]
I cannot help on OCaml-related issues, only on `coq-of-ocaml` related ones. Before running `coq-of-ocaml` you need to have a project successfully compiling in OCaml.

**Comment by clarus** [comment]
Closing the issue as no messages for a long time.
