### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by mizlan** [formal-land/coq-of-ocaml#229]
Coq 8.18, OCaml 4.10.2

when running `make -C proofs`

```
COQC List.v
File "./List.v", line 163, characters 0-374:
Error:
Unable to satisfy the following constraints:
In environment:
merge : forall A : Type, (A -> A -> Z) -> list A -> list A -> list A
A : Type
cmp : A -> A -> Z
l1, l3 : list A
merge_aux : list A -> list A
l2, l, l0 : list A
h1 : A
t1 : list A
h2 : A
t2 : list A

?H : "StrictOrder ?R"

?H0 : "OrderDec ?H"
```

**Comment by mizlan** [comment]
It seems `Z_le_dec` works in place of `Stdlib.le` in the `merge` function in `proofs/List.v`

**Comment by clarus** [comment]
OK thanks for the report! I am able to reproduce the bug, looking for a fix.

**Comment by clarus** [comment]
The issue should now be fixed on the `main` branch thanks to https://github.com/formal-land/coq-of-ocaml/pull/230 !
